application: rs-bigben
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  script: web/main.py

- url: /index\.html
  script: web/main.py

- url: /tasks/weather
  script: weather.py
  login: admin

- url: /tasks/bigben
  script: bigben.py
  login: admin

- url: /tasks/twitter
  script: test.py
  login: admin
